server:
    port: 9100

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/member?useUnicode=true&characterEncoding=utf8
        username: T00001
        password: 9527
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        mode: HTML
